version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install uv
      - cd backend
      - uv sync --no-dev
      - pip install pytest
  build:
    commands:
      - pytest
